apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .NAME }}
  namespace: {{ .NAMESPACE }}
spec:
  replicas: {{ .REPLICAS }}
  selector:
    matchLabels:
      app: {{ .NAME }}
  template:
    metadata:
      labels:
        app: {{ .NAME }}
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 40
      serviceAccountName: analytic
      containers:
        - name: {{ .NAME }}
          image: {{ .IMAGE_NAME }}
          imagePullPolicy: Always
          readinessProbe:
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3
            httpGet:
              path: /api/ready
              port: 8000
          livenessProbe:
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 3
            failureThreshold: 3
            httpGet:
              path: /api/health
              port: 8000
          env:
            - name: ENV
              value: "PRODUCTION"
            - name: PORT
              value: "8000"
            - name: LOG_LEVEL
              value: "INFO"
            - name: SQS_URL
              value: {{ .SQS_URL }}
            - name: AWS_REGION
              value: {{ .SQS_AWS_REGION }}
            - name: PPROF_ENABLED
              value: "{{ .PPROF_ENABLED }}"
            - name: P2P_NETWORK
              value: {{ .P2P_NETWORK }}
            - name: INFLUX_URL
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: influxdb-url
            - name: INFLUX_TOKEN
              valueFrom:
                secretKeyRef:
                  name: influxdb
                  key: token
            - name: INFLUX_ORGANIZATION
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: influxdb-organization
            - name: INFLUX_BUCKET_INFINITE
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: influxdb-bucket-infinite
            - name: INFLUX_BUCKET_30_DAYS
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: influxdb-bucket-30-days
            - name: INFLUX_BUCKET_24_HOURS
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: influxdb-bucket-24-hours
            - name: CACHE_CHANNEL
              value: {{ .CACHE_CHANNEL }}
            - name: CACHE_URL
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: redis-uri
          resources:
            limits:
              memory: {{ .RESOURCES_LIMITS_MEMORY }}
              cpu: {{ .RESOURCES_LIMITS_CPU }}
            requests:
              memory: {{ .RESOURCES_REQUESTS_MEMORY }}
              cpu: {{ .RESOURCES_REQUESTS_CPU }}