build:
	make -C analytics/ build
	make -C api/ build
	make -C core-contract-watcher/ build
	make -C contract-watcher/ build
	make -C fly/ build
	make -C parser/ build
	make -C spy/ build
	make -C tx-tracker/ build
	
test:
	cd analytics && go test -v -cover ./...
	cd api && go test -v -cover ./...
	cd core-contract-watcher && go test -v -cover ./...
	cd contract-watcher && go test -v -cover ./...
	cd fly && go test -v -cover ./...
	cd parser && go test -v -cover ./...
	cd spy && go test -v -cover ./...
	cd tx-tracker && go test -v -cover ./...

.PHONY: build test
