SHELL := /bin/bash

build:
	make -C analytics/ build
	make -C api/ build
	make -C fly/ build
	make -C spy/ build
	make -C parser/ build
	make -C tx-tracker/ build
	make -C contract-watcher/ build
	make -C event-watcher/ build
	
doc:
	make -C api/ doc

test:
	cd analytics && go test -v -cover ./...
	cd api && go test -v -cover ./...
	cd fly && go test -v -cover ./...
	cd spy && go test -v -cover ./...
	cd parser && go test -v -cover ./...
	cd tx-tracker && go test -v -cover ./...
	cd contract-watcher && go test -v -cover ./...
	cd event-watcher && go test -v -cover ./...

.PHONY: build doc test
