---
kind: ConfigMap
apiVersion: v1
metadata:
  name: config
  namespace: { { .NAMESPACE } }
data:
  mongo-database: { { .MONGODB_DATABASE } }
  redis-uri: { { .REDIS_URI } }
  redis-prefix: { { .REDIS_PREFIX } }
  influxdb-url: { { .INFLUX_URL } }
  influxdb-organization: { { .INFLUX_ORGANIZATION } }
  influxdb-bucket-infinite: { { .INFLUX_BUCKET_INFINITE } }
  influxdb-bucket-30-days: { { .INFLUX_BUCKET_30_DAYS } }
  influxdb-bucket-24-hours: { { .INFLUX_BUCKET_24_HOURS } }
  protocols-activity-version: { { .PROTOCOLS_ACTIVITY_VERSION } }
  protocols-stats-version: { { .PROTOCOLS_STATS_VERSION } }
