---
kind: Secret
apiVersion: v1
metadata:
  name: mongodb
  namespace: {{ .NAMESPACE }}
data:
  mongo-uri: {{ .MONGODB_URI | b64enc }}
type: Opaque
---
kind: Secret
apiVersion: v1
metadata:
  name: influxdb
  namespace: {{ .NAMESPACE }}
data:
  token: {{ .INFLUX_TOKEN | b64enc }}
type: Opaque
---
kind: Secret
apiVersion: v1
metadata:
  name: opsgenie
  namespace: {{ .NAMESPACE }}
data:
  api-key: {{ .ALERT_API_KEY | b64enc }}
type: Opaque