---
kind: Secret
apiVersion: v1
metadata:
  name: mongodb
  namespace: {{ .NAMESPACE }}
data:
  mongo-uri: {{ .MONGODB_URI }}
type: Opaque
---
kind: Secret
apiVersion: v1
metadata:
  name: influxdb
  namespace: {{ .NAMESPACE }}
data:
  token: {{ .INFLUX_TOKEN }}
type: Opaque