apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .NAME }}
  namespace: {{ .NAMESPACE }}
spec:
  replicas: {{ .REPLICAS }}
  selector:
    matchLabels:
      app: {{ .NAME }}
  template:
    metadata:
      labels:
        app: {{ .NAME }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 40
      serviceAccountName: fly-events-processor
      containers:
        - name: {{ .NAME }}
          image: {{ .IMAGE_NAME }}
          imagePullPolicy: Always
          volumeMounts:
            - name: fly-event-processor-config
              mountPath: /opt/fly-event-processor
          readinessProbe:
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3
            httpGet:
              path: /api/ready
              port: 8000
          livenessProbe:
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 3
            failureThreshold: 3
            httpGet:
              path: /api/health
              port: 8000
          env:
            - name: ENVIRONMENT
              value: {{ .ENVIRONMENT }}
            - name: PORT
              value: "8000"
            - name: LOG_LEVEL
              value: "INFO"
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: mongo-uri
            - name: MONGODB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: mongo-database
            - name: DUPLICATE_VAA_SQS_URL
              valueFrom:
                configMapKeyRef:
                  name: fly-event-processor
                  key: duplicate-vaa-sqs-url
            - name: GOVERNOR_SQS_URL
              valueFrom:
                configMapKeyRef:
                  name: fly-event-processor
                  key: governor-sqs-url
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: fly-event-processor
                  key: aws-region
            - name: PPROF_ENABLED
              value: "{{ .PPROF_ENABLED }}"
            - name: P2P_NETWORK
              value: {{ .P2P_NETWORK }}
            - name: ALERT_ENABLED
              value: "{{ .ALERT_ENABLED }}"
            - name: ALERT_API_KEY
              valueFrom:
                secretKeyRef:
                  name: opsgenie
                  key: api-key
            - name: METRICS_ENABLED
              value: "{{ .METRICS_ENABLED }}"
            - name: CONSUMER_WORKER_SIZE
              value: "{{ .CONSUMER_WORKER_SIZE }}"
            - name: GUARDIAN_API_PROVIDER_PATH
              value: "/opt/fly-event-processor/guardian-provider.json"
            - name: TX_TRACKER_URL
              value: "{{ .TX_TRACKER_URL }}"
            - name: TX_TRACKER_TIMEOUT
              value: "{{ .TX_TRACKER_TIMEOUT }}"
          resources:
            limits:
              memory: {{ .RESOURCES_LIMITS_MEMORY }}
              cpu: {{ .RESOURCES_LIMITS_CPU }}
            requests:
              memory: {{ .RESOURCES_REQUESTS_MEMORY }}
              cpu: {{ .RESOURCES_REQUESTS_CPU }}
      volumes:
        - name: fly-event-processor-config
          secret:
            secretName: guardian-provider
            items:
            - key: guardian-provider.json
              path: guardian-provider.json
