---
kind: Secret
apiVersion: v1
metadata:
  name: blockchain
  namespace: {{ .NAMESPACE }}
data:
  ankr-url: {{ .ANKR_URL | b64enc }}
  solana-url: {{ .SOLANA_URL | b64enc }}
  terra-url: {{ .TERRA_URL | b64enc }}
  aptos-url: {{ .APTOS_URL | b64enc }}
type: Opaque
