apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blockchain-watcher-metadata-pvc
  namespace: {{ .NAMESPACE }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
  storageClassName: gp2
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: blockchain-watcher-metadata-pv
  namespace: {{ .NAMESPACE }}
spec:
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
  capacity:
    storage: 50Mi
  storageClassName: gp2
  hostPath:
    path: /home/node/app/metadata-repo