apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blockchain-watcher-metadata-pvc
  namespace: {{ .NAMESPACE }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: blockchain-watcher-metadata-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: blockchain-watcher-metadata-pv
  namespace: {{ .NAMESPACE }}
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 50Mi
  hostPath:
    path: /home/node/app/metadata-repo