apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ .NAME }}
  namespace: {{ .NAMESPACE }}
spec:
  scaleTargetRef:
    name: {{ .NAME }}
  minReplicaCount: 2
  maxReplicaCount: 10
  triggers:
  - type: memory
    metricType: Utilization # Allowed types are 'Utilization' or 'AverageValue'
    metadata:
      value: "50"