apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .NAME }}
  namespace: {{ .NAMESPACE }}
spec:
  replicas: {{ .REPLICAS }}
  selector:
    matchLabels:
      app: {{ .NAME }}
  template:
    metadata:
      labels:
        app: {{ .NAME }}
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 40
      #serviceAccountName: event-watcher
      containers:
        - name: {{ .NAME }}
          image: {{ .IMAGE_NAME }}
          imagePullPolicy: Always
          readinessProbe:
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3
            httpGet:
              path: /ready
              port: {{ .PORT }}
          livenessProbe:
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 3
            failureThreshold: 3
            httpGet:
              path: /health
              port: {{ .PORT }}
          env:
            - name: ENVIRONMENT
              value: {{ .ENVIRONMENT }}
            - name: PORT
              value: "{{ .PORT }}"
            - name: LOG_LEVEL
              value: "{{ .LOG_LEVEL }}"
            - name: DB_SOURCE
              value: {{ .DB_SOURCE }}
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: mongo-uri
            - name: MONGODB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: mongo-database
            - name: SNS_SOURCE
              value: {{ .SNS_SOURCE }}
            - name: AWS_SNS_SUBJECT
              value: {{ .AWS_SNS_SUBJECT }}
            - name: AWS_SNS_TOPIC_ARN
              value: {{ .AWS_SNS_TOPIC_ARN }}
            - name: AWS_SNS_REGION
              value: {{ .AWS_SNS_REGION }}
            - name: ETH_RPC
              value: {{ .ETH_RPC }}              
          resources:
            limits:
              memory: {{ .RESOURCES_LIMITS_MEMORY }}
              cpu: {{ .RESOURCES_LIMITS_CPU }}
            requests:
              memory: {{ .RESOURCES_REQUESTS_MEMORY }}
              cpu: {{ .RESOURCES_REQUESTS_CPU }}