---
kind: ConfigMap
apiVersion: v1
metadata:
  name: jobs
  namespace: {{ .NAMESPACE }}
data:
  aws-region: {{ .AWS_REGION }}
  aws-bucket: {{ .AWS_BUCKET }}
  coingecko-url: {{ .COINGECKO_URL }}
  coingecko-header-key: {{ .COINGECKO_HEADER_KEY }}
