apiVersion: batch/v1
kind: CronJob
metadata:
  name: contributors-stats-1m
  namespace: { { .NAMESPACE } }
spec: #cronjob specs
  schedule: { { .CONTRIBUTORS_ACTIVITY_CRONTAB_SCHEDULE } }
  jobTemplate:
    spec: # job specs
      template:
        spec: # pod specs
          containers:
            - name: contributors-stats-1m
              image: { { .IMAGE_NAME } }
              imagePullPolicy: Always
              env:
                - name: ENVIRONMENT
                  value: { { .ENVIRONMENT } }
                - name: LOG_LEVEL
                  value: { { .LOG_LEVEL } }
                - name: JOB_ID
                  value: JOB_CONTRIBUTORS_STATS
                - name: INFLUX_URL
                  valueFrom:
                    configMapKeyRef:
                      name: config
                      key: influxdb-url
                - name: INFLUX_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: influxdb
                      key: token
                - name: INFLUX_ORGANIZATION
                  valueFrom:
                    configMapKeyRef:
                      name: config
                      key: influxdb-organization
                - name: INFLUX_BUCKET_30_DAYS
                  valueFrom:
                    configMapKeyRef:
                      name: config
                      key: influxdb-bucket-30-days
                - name: ACTIVITY_VERSION
                  valueFrom:
                    configMapKeyRef:
                      name: config
                      key: contributors-activity-version
          restartPolicy: OnFailure