apiVersion: batch/v1
kind: Job
metadata:
  name: migrate-native-tx-hash
  namespace: {{ .NAMESPACE }}
spec:
  template:
    metadata:
      labels:
        app: migrate-native-tx-hash
    spec:
      restartPolicy: Never
      terminationGracePeriodSeconds: 40
      containers:
        - name: migrate-native-tx-hash
          image: {{ .IMAGE_NAME }}
          imagePullPolicy: Always
          env:
            - name: ENVIRONMENT
              value: {{ .ENVIRONMENT }}
            - name: P2P_NETWORK
              value: {{ .P2P_NETWORK }}
            - name: LOG_LEVEL
              value: {{ .LOG_LEVEL }}
            - name: JOB_ID
              value: JOB_MIGRATE_NATIVE_TX_HASH
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: mongo-uri
            - name: MONGODB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: mongo-database
            - name: PAGE_SIZE
              value: "1000"