apiVersion: batch/v1
kind: CronJob
metadata:
  name: notional
  namespace: {{ .NAMESPACE }}
spec:
  schedule: "{{ .CRONTAB_SCHEDULE }}"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{ .NAME }}
            image: {{ .IMAGE_NAME }}
            imagePullPolicy: Always
            env:
              - name: ENV
                value: {{ .ENVIRONMENT }}
              - name: P2P_NETWORK
                value: {{ .P2P_NETWORK }}
              - name: LOG_LEVEL
                value: {{ .LOG_LEVEL }}
              - name: JOB_ID
                value: JOB_NOTIONAL_USD
              - name: COINGECKO_URL
                value: {{ .COINGECKO_URL }}
              - name: NOTIONAL_CHANNEL
                value: {{ .NOTIONAL_CHANNEL }}
              - name: CACHE_URL
                valueFrom:
                  configMapKeyRef:
                    name: config
                    key: redis-uri
              - name: CACHE_PREFIX
                value: {{ .CACHE_PREFIX }}                    
          restartPolicy: OnFailure
