apiVersion: batch/v1
kind: CronJob
metadata:
  name: protocols-activity-1h
  namespace: {{ .NAMESPACE }}
spec: #cronjob specs
  schedule: {{ .PROTOCOLS_ACTIVITY_CRONTAB_SCHEDULE }}
  jobTemplate:
    spec: # job specs
      template:
        spec: # pod specs
          containers:
            - name: protocols-activity-1h
              image: {{ .IMAGE_NAME }}
              imagePullPolicy: Always
              env:
                - name: ENVIRONMENT
                  value: {{ .ENVIRONMENT }}
                - name: LOG_LEVEL
                  value: {{ .LOG_LEVEL }}
                - name: JOB_ID
                  value: JOB_PROTOCOLS_STATS
                - name: INFLUX_URL
                  valueFrom:
                    configMapKeyRef:
                      name: config
                      key: influxdb-url
                - name: INFLUX_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: influxdb
                      key: token
                - name: INFLUX_ORGANIZATION
                  valueFrom:
                    configMapKeyRef:
                      name: config
                      key: influxdb-organization
                - name: INFLUX_BUCKET_30_DAYS
                  valueFrom:
                    configMapKeyRef:
                      name: config
                      key: influxdb-bucket-30-days
                - name: ACTIVITY_VERSION
                  valueFrom:
                    configMapKeyRef:
                      name: config
                      key: protocols-activity-version
                - name: PROTOCOLS_JSON
                  value: {{ .PROTOCOLS_JSON }}
          restartPolicy: OnFailure