---
kind: Secret
apiVersion: v1
metadata:
  name: jobs
  namespace: {{ .NAMESPACE }}
data:
  coingecko-api-key: {{ .COINGECKO_API_KEY | b64enc }}
  arkham-api-key: {{ .ARKHAM_API_KEY | b64enc }}
  solana-url: {{ .SOLANA_URL | b64enc }}

type: Opaque
