// Code generated by MockGen. DO NOT EDIT.
// Source: mongo_repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	pipeline "github.com/wormhole-foundation/wormhole-explorer/pipeline/pipeline"
)

// MockIRepository is a mock of IRepository interface.
type MockIRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIRepositoryMockRecorder
}

// MockIRepositoryMockRecorder is the mock recorder for MockIRepository.
type MockIRepositoryMockRecorder struct {
	mock *MockIRepository
}

// NewMockIRepository creates a new mock instance.
func NewMockIRepository(ctrl *gomock.Controller) *MockIRepository {
	mock := &MockIRepository{ctrl: ctrl}
	mock.recorder = &MockIRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIRepository) EXPECT() *MockIRepositoryMockRecorder {
	return m.recorder
}

// GetVaaIdTxHash mocks base method.
func (m *MockIRepository) GetVaaIdTxHash(ctx context.Context, id string) (*pipeline.VaaIdTxHash, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVaaIdTxHash", ctx, id)
	ret0, _ := ret[0].(*pipeline.VaaIdTxHash)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVaaIdTxHash indicates an expected call of GetVaaIdTxHash.
func (mr *MockIRepositoryMockRecorder) GetVaaIdTxHash(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVaaIdTxHash", reflect.TypeOf((*MockIRepository)(nil).GetVaaIdTxHash), ctx, id)
}

// UpdateVaaDocTxHash mocks base method.
func (m *MockIRepository) UpdateVaaDocTxHash(ctx context.Context, id, txhash string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateVaaDocTxHash", ctx, id, txhash)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateVaaDocTxHash indicates an expected call of UpdateVaaDocTxHash.
func (mr *MockIRepositoryMockRecorder) UpdateVaaDocTxHash(ctx, id, txhash interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateVaaDocTxHash", reflect.TypeOf((*MockIRepository)(nil).UpdateVaaDocTxHash), ctx, id, txhash)
}
