---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .NAME }}
  namespace: {{ .NAMESPACE }}
spec:
  replicas: {{ .REPLICAS }}
  selector:
    matchLabels:
      app: {{ .NAME }}
  template:
    metadata:
      labels:
        app: {{ .NAME }}
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 40
      containers:
        - name: {{ .NAME }}
          image: {{ .IMAGE_NAME }}
          imagePullPolicy: Always
          readinessProbe:
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3
            httpGet:
              path: /api/ready
              port: 8000
          livenessProbe:
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 3
            failureThreshold: 3
            httpGet:
              path: /api/health
              port: 8000
          env:
            - name: ENV
              value: "PRODUCTION"
            - name: MONITORING_PORT
              value: "8000"
            - name: LOG_LEVEL
              value: "INFO"
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: mongo-uri
            - name: MONGODB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: mongo-database
            - name: SQS_URL
              value: {{ .SQS_URL }}
            - name: AWS_REGION
              value: {{ .SQS_AWS_REGION }}
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: tx-tracker-sqs
                  key: aws-access-key-id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: tx-tracker-sqs
                  key: aws-secret-access-key
            - name: VAA_PAYLOAD_PARSER_URL
              value: {{ .VAA_PAYLOAD_PARSER_URL }}
            - name: VAA_PAYLOAD_PARSER_TIMEOUT
              value: "{{ .VAA_PAYLOAD_PARSER_TIMEOUT }}"
            - name: ANKR_API_KEY
              value: {{ .ANKR_API_KEY }}
            - name: ANKR_BASE_URL
              value: {{ .ANKR_BASE_URL }}
            - name: ANKR_REQUESTS_PER_MINUTE
              value: "{{ .ANKR_REQUESTS_PER_MINUTE }}"
            - name: ARBITRUM_API_KEY
              value: {{ .ARBITRUM_API_KEY }}
            - name: ARBITRUM_BASE_URL
              value: {{ .ARBITRUM_BASE_URL }}
            - name: ARBITRUM_REQUESTS_PER_MINUTE
              value: "{{ .ARBITRUM_REQUESTS_PER_MINUTE }}"
            - name: AVALANCHE_API_KEY
              value: {{ .AVALANCHE_API_KEY }}
            - name: AVALANCHE_BASE_URL
              value: {{ .AVALANCHE_BASE_URL }}
            - name: AVALANCHE_REQUESTS_PER_MINUTE
              value: "{{ .AVALANCHE_REQUESTS_PER_MINUTE }}"
            - name: BSC_API_KEY
              value: {{ .BSC_API_KEY }}
            - name: BSC_BASE_URL
              value: {{ .BSC_BASE_URL }}
            - name: BSC_REQUESTS_PER_MINUTE
              value: "{{ .BSC_REQUESTS_PER_MINUTE }}"
            - name: CELO_API_KEY
              value: {{ .CELO_API_KEY }}
            - name: CELO_BASE_URL
              value: {{ .CELO_BASE_URL }}
            - name: CELO_REQUESTS_PER_MINUTE
              value: "{{ .CELO_REQUESTS_PER_MINUTE }}"
            - name: ETH_API_KEY
              value: {{ .ETH_API_KEY }}
            - name: ETH_BASE_URL
              value: {{ .ETH_BASE_URL }}
            - name: ETH_REQUESTS_PER_MINUTE
              value: "{{ .ETH_REQUESTS_PER_MINUTE }}"
            - name: FANTOM_API_KEY
              value: {{ .FANTOM_API_KEY }}
            - name: FANTOM_BASE_URL
              value: {{ .FANTOM_BASE_URL }}
            - name: FANTOM_REQUESTS_PER_MINUTE
              value: "{{ .FANTOM_REQUESTS_PER_MINUTE }}"
            - name: OPTIMISM_API_KEY
              value: {{ .OPTIMISM_API_KEY }}
            - name: OPTIMISM_BASE_URL
              value: {{ .OPTIMISM_BASE_URL }}
            - name: OPTIMISM_REQUESTS_PER_MINUTE
              value: "{{ .OPTIMISM_REQUESTS_PER_MINUTE }}"
            - name: POLYGON_API_KEY
              value: {{ .POLYGON_API_KEY }}
            - name: POLYGON_BASE_URL
              value: {{ .POLYGON_BASE_URL }}
            - name: POLYGON_REQUESTS_PER_MINUTE
              value: "{{ .POLYGON_REQUESTS_PER_MINUTE }}"
            - name: SOLANA_BASE_URL
              value: {{ .SOLANA_BASE_URL }}
            - name: SOLANA_REQUESTS_PER_MINUTE
              value: "{{ .SOLANA_REQUESTS_PER_MINUTE }}"
            - name: TERRA_BASE_URL
              value: {{ .TERRA_BASE_URL }}
            - name: TERRA_REQUESTS_PER_MINUTE
              value: "{{ .TERRA_REQUESTS_PER_MINUTE }}"
          resources:
            limits:
              memory: {{ .RESOURCES_LIMITS_MEMORY }}
              cpu: {{ .RESOURCES_LIMITS_CPU }}
            requests:
              memory: {{ .RESOURCES_REQUESTS_MEMORY }}
              cpu: {{ .RESOURCES_REQUESTS_CPU }}
