---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .NAME }}
  namespace: {{ .NAMESPACE }}
spec:
  replicas: {{ .REPLICAS }}
  selector:
    matchLabels:
      app: {{ .NAME }}
  template:
    metadata:
      labels:
        app: {{ .NAME }}
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 40
      containers:
        - name: {{ .NAME }}
          image: {{ .IMAGE_NAME }}
          imagePullPolicy: Always
          readinessProbe:
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3
            httpGet:
              path: /api/ready
              port: 8000
          livenessProbe:
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 3
            failureThreshold: 3
            httpGet:
              path: /api/health
              port: 8000
          env:
            - name: ENV
              value: "PRODUCTION"
            - name: MONITORING_PORT
              value: "8000"
            - name: LOG_LEVEL
              value: "DEBUG"
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: mongo-uri
            - name: MONGODB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: mongo-database
            - name: SQS_URL
              value: {{ .SQS_URL }}
            - name: AWS_REGION
              value: {{ .SQS_AWS_REGION }}
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: tx-tracker-sqs
                  key: aws-access-key-id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: tx-tracker-sqs
                  key: aws-secret-access-key
            - name: VAA_PAYLOAD_PARSER_URL
              value: {{ .VAA_PAYLOAD_PARSER_URL }}
            - name: VAA_PAYLOAD_PARSER_TIMEOUT
              value: "{{ .VAA_PAYLOAD_PARSER_TIMEOUT }}"
            - name: ANKR_BASE_URL
              value: "https://rpc.ankr.com/multichain"
            - name: ANKR_REQUESTS_PER_MINUTE
              value: "30"
            - name: SOLANA_BASE_URL
              value: "https://api.mainnet-beta.solana.com"
            - name: SOLANA_REQUESTS_PER_MINUTE
              value: "8"
            - name: TERRA_BASE_URL
              value: "https://lcd.terra.dev"
            - name: TERRA_REQUESTS_PER_MINUTE
              value: "6"
          resources:
            limits:
              memory: {{ .RESOURCES_LIMITS_MEMORY }}
              cpu: {{ .RESOURCES_LIMITS_CPU }}
            requests:
              memory: {{ .RESOURCES_REQUESTS_MEMORY }}
              cpu: {{ .RESOURCES_REQUESTS_CPU }}
