apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .NAME }}
  namespace: {{ .NAMESPACE }}
spec:
  replicas: {{ .REPLICAS }}
  selector:
    matchLabels:
      app: {{ .NAME }}
  template:
    metadata:
      labels:
        app: {{ .NAME }}
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 40
      serviceAccountName: tx-tracker
      containers:
        - name: {{ .NAME }}
          image: {{ .IMAGE_NAME }}
          imagePullPolicy: Always
          readinessProbe:
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3
            httpGet:
              path: /api/ready
              port: 8000
          livenessProbe:
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 3
            failureThreshold: 3
            httpGet:
              path: /api/health
              port: 8000
          env:
            - name: ENV
              value: "PRODUCTION"
            - name: MONITORING_PORT
              value: "8000"
            - name: LOG_LEVEL
              value: "INFO"
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: mongo-uri
            - name: MONGODB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: mongo-database
            - name: SQS_URL
              value: {{ .SQS_URL }}
            - name: AWS_REGION
              value: {{ .SQS_AWS_REGION }}
            - name: APTOS_BASE_URL
              value: {{ .APTOS_BASE_URL }}
            - name: APTOS_REQUESTS_PER_MINUTE
              value: "{{ .APTOS_REQUESTS_PER_MINUTE }}"
            - name: ARBITRUM_BASE_URL
              value: {{ .ARBITRUM_BASE_URL }}
            - name: ARBITRUM_REQUESTS_PER_MINUTE
              value: "{{ .ARBITRUM_REQUESTS_PER_MINUTE }}"
            - name: AVALANCHE_BASE_URL
              value: {{ .AVALANCHE_BASE_URL }}
            - name: AVALANCHE_REQUESTS_PER_MINUTE
              value: "{{ .AVALANCHE_REQUESTS_PER_MINUTE }}"
            - name: BSC_BASE_URL
              value: {{ .BSC_BASE_URL }}
            - name: BSC_REQUESTS_PER_MINUTE
              value: "{{ .BSC_REQUESTS_PER_MINUTE }}"
            - name: CELO_BASE_URL
              value: {{ .CELO_BASE_URL }}
            - name: CELO_REQUESTS_PER_MINUTE
              value: "{{ .CELO_REQUESTS_PER_MINUTE }}"
            - name: ETHEREUM_BASE_URL
              value: {{ .ETHEREUM_BASE_URL }}
            - name: ETHEREUM_REQUESTS_PER_MINUTE
              value: "{{ .ETHEREUM_REQUESTS_PER_MINUTE }}"
            - name: FANTOM_BASE_URL
              value: {{ .FANTOM_BASE_URL }}
            - name: FANTOM_REQUESTS_PER_MINUTE
              value: "{{ .FANTOM_REQUESTS_PER_MINUTE }}"
            - name: MOONBEAM_BASE_URL
              value: {{ .MOONBEAM_BASE_URL }}
            - name: MOONBEAM_REQUESTS_PER_MINUTE
              value: "{{ .MOONBEAM_REQUESTS_PER_MINUTE }}"
            - name: OPTIMISM_BASE_URL
              value: {{ .OPTIMISM_BASE_URL }}
            - name: OPTIMISM_REQUESTS_PER_MINUTE
              value: "{{ .OPTIMISM_REQUESTS_PER_MINUTE }}"
            - name: POLYGON_BASE_URL
              value: {{ .POLYGON_BASE_URL }}
            - name: POLYGON_REQUESTS_PER_MINUTE
              value: "{{ .POLYGON_REQUESTS_PER_MINUTE }}"
            - name: SOLANA_BASE_URL
              value: {{ .SOLANA_BASE_URL }}
            - name: SOLANA_REQUESTS_PER_MINUTE
              value: "{{ .SOLANA_REQUESTS_PER_MINUTE }}"
            - name: SUI_BASE_URL
              value: {{ .SUI_BASE_URL }}
            - name: SUI_REQUESTS_PER_MINUTE
              value: "{{ .SUI_REQUESTS_PER_MINUTE }}"
          resources:
            limits:
              memory: {{ .RESOURCES_LIMITS_MEMORY }}
              cpu: {{ .RESOURCES_LIMITS_CPU }}
            requests:
              memory: {{ .RESOURCES_REQUESTS_MEMORY }}
              cpu: {{ .RESOURCES_REQUESTS_CPU }}
