apiVersion: v1
kind: PersistentVolume
metadata:
  name: wormhole-explorer-mongo-pv
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 500Gi
  hostPath:
    path: "/data/db"
