apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wormhole-explorer-mongo-pvc
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
