---          
apiVersion: v1
kind: Service
metadata:
  name: {{ .NAME }}-eth-2
  namespace: {{ .NAMESPACE }}
  labels:
    app: {{ .NAME }}-eth-2
spec:
  selector:
    app: {{ .NAME }}-eth-2
  ports:
    - port: {{ .PORT }}
      targetPort: {{ .PORT }}
      name: {{ .NAME }}-eth-2
      protocol: TCP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blockchain-watcher-eth-2-pvc
  namespace: {{ .NAMESPACE }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
  storageClassName: gp2
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .NAME }}-eth-2-jobs
  namespace: {{ .NAMESPACE }}
data:
  testnet-jobs.json: |-
    [
      {
        "id": "poll-log-message-published-bsc",
        "chain": "bsc",
        "source": {
          "action": "PollEvmLogs",
          "config": {
            "blockBatchSize": 100,
            "commitment": "latest",
            "interval": 15000,
            "addresses": ["0x68605AD7b15c732a30b1BbC62BE8F2A509D74b4D"],
            "chain": "bsc"
          }
        },
        "handlers": [
          {
            "action": "HandleEvmLogs",
            "target": "sns",
            "mapper": "evmLogMessagePublishedMapper",
            "config": {
              "abi": "event LogMessagePublished(address indexed sender, uint64 sequence, uint32 nonce, bytes payload, uint8 consistencyLevel)",
              "filter": {
                "addresses": ["0x68605AD7b15c732a30b1BbC62BE8F2A509D74b4D"],
                "topics": ["0x6eb224fb001ed210e379b335e35efe88672a8ce935d981a6896b27ffdf52a3b2"]
              }
            }
          }
        ]
      }
    ]
  mainnet-jobs.json: |-
    [
      {
        "id": "poll-log-message-published-bsc",
        "chain": "bsc",
        "source": {
          "action": "PollEvmLogs",
          "config": {
            "blockBatchSize": 100,
            "commitment": "latest",
            "interval": 5000,
            "addresses": ["0x98f3c9e6E3fAce36bAAd05FE09d375Ef1464288B"],
            "chain": "bsc"
          }
        },
        "handlers": [
          {
            "action": "HandleEvmLogs",
            "target": "sns",
            "mapper": "evmLogMessagePublishedMapper",
            "config": {
              "abi": "event LogMessagePublished(address indexed sender, uint64 sequence, uint32 nonce, bytes payload, uint8 consistencyLevel)",
              "filter": {
                "addresses": ["0x98f3c9e6E3fAce36bAAd05FE09d375Ef1464288B"],
                "topics": ["0x6eb224fb001ed210e379b335e35efe88672a8ce935d981a6896b27ffdf52a3b2"]
              }
            }
          }
        ]
      }
    ]
---
apiVersion: v1
kind: Pod
metadata:
  name: {{ .NAME }}-eth-2
  namespace: {{ .NAMESPACE }}
  labels:
    app: {{ .NAME }}-eth-2
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{ .PORT }}"
spec:
  restartPolicy: Always
  terminationGracePeriodSeconds: 30
  serviceAccountName: event-watcher
  containers:
    - name: {{ .NAME }}
      image: {{ .IMAGE_NAME }}
      env:
        - name: NODE_ENV
          value: {{ .NODE_ENV }}
        - name: PORT
          value: "{{ .PORT }}"
        - name: LOG_LEVEL
          value: {{ .LOG_LEVEL }}
        - name: BLOCKCHAIN_ENV
          value: {{ .BLOCKCHAIN_ENV }}
        - name: DRY_RUN_ENABLED
          value: "{{ .DRY_RUN_ENABLED }}"
        - name: SNS_TOPIC_ARN
          value: {{ .SNS_TOPIC_ARN }}
        - name: SNS_REGION
          value: {{ .SNS_REGION }}
        - name: JOBS_DIR
          value: /home/node/app/jobs
      resources:
        limits:
          memory: {{ .RESOURCES_LIMITS_MEMORY }}
          cpu: {{ .RESOURCES_LIMITS_CPU }}
        requests:
          memory: {{ .RESOURCES_REQUESTS_MEMORY }}
          cpu: {{ .RESOURCES_REQUESTS_CPU }}
      volumeMounts:
        - name: metadata-volume
          mountPath: /home/node/app/metadata-repo 
        - name: jobs-volume
          mountPath: /home/node/app/jobs
  volumes:
    - name: metadata-volume
      persistentVolumeClaim:
        claimName: blockchain-watcher-eth-2-pvc
    - name: jobs-volume
      configMap:
        name: {{ .NAME }}-eth-2-jobs
        items:
          - key: {{ .BLOCKCHAIN_ENV }}-jobs.json
            path: jobs.json
