---          
apiVersion: v1
kind: Service
metadata:
  name: {{ .NAME }}-message-sent-events-1
  namespace: {{ .NAMESPACE }}
  labels:
    app: {{ .NAME }}-message-sent-events-1
spec:
  selector:
    app: {{ .NAME }}-message-sent-events-1
  ports:
    - port: {{ .PORT }}
      targetPort: {{ .PORT }}
      name: {{ .NAME }}-message-sent-events-1
      protocol: TCP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blockchain-watcher-message-sent-events-1-pvc
  namespace: {{ .NAMESPACE }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
  storageClassName: gp2
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .NAME }}-message-sent-events-1-jobs
  namespace: {{ .NAMESPACE }}
data:
  testnet-jobs.json: |-
    [
    ]
  mainnet-jobs.json: |-
    [
      {
        "id": "poll-log-message-sent-ethereum",
        "chain": "ethereum",
        "source": {
          "action": "PollEvm",
          "records": "GetEvmTransactions",
          "config": {
            "blockBatchSize": 100,
            "commitment": "latest",
            "interval": 15000,
            "filters": [
              {
                "addresses": [],
                "type": "CCTP",
                "topics": ["0x8c5261668696ce22758910d05bab8f186d6eb247ceac2af2e82c7dc17669b036"],
                "strategy": "GetTransactionsByLogFiltersStrategy"
              }
            ],
            "chain": "ethereum",
            "chainId": 2
          }
        },
        "handlers": [
          {
            "action": "HandleEvmTransactions",
            "target": "influx",
            "mapper": "evmLogCircleMessageSentMapper",
            "config": {
              "abi": "event MessageSent (bytes message)",
              "metricName": "process_message_sent_event",
              "environment": "mainnet"
            }
          }
        ]
      },
      {
        "id": "poll-log-message-sent-avalanche",
        "chain": "avalanche",
        "source": {
          "action": "PollEvm",
          "records": "GetEvmTransactions",
          "config": {
            "blockBatchSize": 100,
            "commitment": "latest",
            "interval": 15000,
            "filters": [
              {
                "addresses": [],
                "type": "CCTP",
                "topics": ["0x8c5261668696ce22758910d05bab8f186d6eb247ceac2af2e82c7dc17669b036"],
                "strategy": "GetTransactionsByLogFiltersStrategy"
              }
            ],
            "chain": "avalanche",
            "chainId": 6
          }
        },
        "handlers": [
          {
            "action": "HandleEvmTransactions",
            "target": "influx",
            "mapper": "evmLogCircleMessageSentMapper",
            "config": {
              "abi": "event MessageSent (bytes message)",
              "metricName": "process_message_sent_event",
              "environment": "mainnet"
            }
          }
        ]
      },
      {
        "id": "poll-log-message-sent-optimism",
        "chain": "optimism",
        "source": {
          "action": "PollEvm",
          "records": "GetEvmTransactions",
          "config": {
            "blockBatchSize": 100,
            "commitment": "latest",
            "interval": 15000,
            "filters": [
              {
                "addresses": [],
                "type": "CCTP",
                "topics": ["0x8c5261668696ce22758910d05bab8f186d6eb247ceac2af2e82c7dc17669b036"],
                "strategy": "GetTransactionsByLogFiltersStrategy"
              }
            ],
            "chain": "optimism",
            "chainId": 24
          }
        },
        "handlers": [
          {
            "action": "HandleEvmTransactions",
            "target": "influx",
            "mapper": "evmLogCircleMessageSentMapper",
            "config": {
              "abi": "event MessageSent (bytes message)",
              "metricName": "process_message_sent_event",
              "environment": "mainnet"
            }
          }
        ]
      },
      {
        "id": "poll-log-message-sent-arbitrum",
        "chain": "arbitrum",
        "source": {
          "action": "PollEvm",
          "records": "GetEvmTransactions",
          "config": {
            "blockBatchSize": 100,
            "commitment": "latest",
            "interval": 15000,
            "filters": [
              {
                "addresses": [],
                "type": "CCTP",
                "topics": ["0x8c5261668696ce22758910d05bab8f186d6eb247ceac2af2e82c7dc17669b036"],
                "strategy": "GetTransactionsByLogFiltersStrategy"
              }
            ],
            "chain": "arbitrum",
            "chainId": 23
          }
        },
        "handlers": [
          {
            "action": "HandleEvmTransactions",
            "target": "influx",
            "mapper": "evmLogCircleMessageSentMapper",
            "config": {
              "abi": "event MessageSent (bytes message)",
              "metricName": "process_message_sent_event",
              "environment": "mainnet"
            }
          }
        ]
      },
      {
        "id": "poll-log-message-sent-base",
        "chain": "base",
        "source": {
          "action": "PollEvm",
          "records": "GetEvmTransactions",
          "config": {
            "blockBatchSize": 100,
            "commitment": "latest",
            "interval": 15000,
            "filters": [
              {
                "addresses": [],
                "type": "CCTP",
                "topics": ["0x8c5261668696ce22758910d05bab8f186d6eb247ceac2af2e82c7dc17669b036"],
                "strategy": "GetTransactionsByLogFiltersStrategy"
              }
            ],
            "chain": "base",
            "chainId": 30
          }
        },
        "handlers": [
          {
            "action": "HandleEvmTransactions",
            "target": "influx",
            "mapper": "evmLogCircleMessageSentMapper",
            "config": {
              "abi": "event MessageSent (bytes message)",
              "metricName": "process_message_sent_event",
              "environment": "mainnet"
            }
          }
        ]
      },
      {
        "id": "poll-log-message-sent-polygon",
        "chain": "polygon",
        "source": {
          "action": "PollEvm",
          "records": "GetEvmTransactions",
          "config": {
            "blockBatchSize": 100,
            "commitment": "latest",
            "interval": 15000,
            "filters": [
              {
                "addresses": [],
                "type": "CCTP",
                "topics": ["0x8c5261668696ce22758910d05bab8f186d6eb247ceac2af2e82c7dc17669b036"],
                "strategy": "GetTransactionsByLogFiltersStrategy"
              }
            ],
            "chain": "polygon",
            "chainId": 5
          }
        },
        "handlers": [
          {
            "action": "HandleEvmTransactions",
            "target": "influx",
            "mapper": "evmLogCircleMessageSentMapper",
            "config": {
              "abi": "event MessageSent (bytes message)",
              "metricName": "process_message_sent_event",
              "environment": "mainnet"
            }
          }
        ]
      }
    ]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .NAME }}-message-sent-events-1
  namespace: {{ .NAMESPACE }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .NAME }}-message-sent-events-1
  template:
    metadata:
      labels:
        app: {{ .NAME }}-message-sent-events-1
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{ .PORT }}"
    spec:
      containers:
        - name: {{ .NAME }}
          env:
            - name: NODE_ENV
              value: {{ .NODE_ENV }}
            - name: PORT
              value: "{{ .PORT }}"
            - name: LOG_LEVEL
              value: {{ .LOG_LEVEL }}
            - name: BLOCKCHAIN_ENV
              value: {{ .BLOCKCHAIN_ENV }}
            - name: DRY_RUN_ENABLED
              value: "{{ .DRY_RUN_ENABLED }}"
            - name: SNS_TOPIC_ARN
              value: {{ .SNS_TOPIC_ARN }}
            - name: SNS_REGION
              value: {{ .SNS_REGION }}
            - name: NODE_OPTIONS
              value: {{ .NODE_OPTIONS }}
            - name: JOBS_DIR
              value: /home/node/app/jobs
            {{ if .ETHEREUM_RPCS }}
            - name: ETHEREUM_RPCS
              value: '{{ .ETHEREUM_RPCS }}'
            {{ end }}
            {{ if .AVALANCHE_RPCS }}
            - name: AVALANCHE_RPCS
              value: '{{ .AVALANCHE_RPCS }}'
            {{ end }}
            {{ if .OPTIMISM_RPCS }}
            - name: OPTIMISM_RPCS
              value: '{{ .OPTIMISM_RPCS }}'
            {{ end }}
            {{ if .POLYGON_RPCS }}
            - name: POLYGON_RPCS
              value: '{{ .POLYGON_RPCS }}'
            {{ end }}
            {{ if .BASE_RPCS }}
            - name: BASE_RPCS
              value: '{{ .BASE_RPCS }}'
            {{ end }}
            {{ if .ARBITRUM_RPCS }}
            - name: ARBITRUM_RPCS
              value: '{{ .ARBITRUM_RPCS }}'
            {{ end }}
          image: {{ .IMAGE_NAME }}
          resources:
            limits:
              cpu: {{ .RESOURCES_LIMITS_CPU }}
              memory: {{ .RESOURCES_LIMITS_MEMORY }}
            requests:
              cpu: {{ .RESOURCES_REQUESTS_CPU }}
              memory: {{ .RESOURCES_REQUESTS_MEMORY }}
          volumeMounts:
            - name: metadata-volume
              mountPath: /home/node/app/metadata-repo 
            - name: jobs-volume
              mountPath: /home/node/app/jobs
      restartPolicy: Always
      serviceAccountName: blockchain-watcher
      terminationGracePeriodSeconds: 30
      volumes:
        - name: metadata-volume
          persistentVolumeClaim:
            claimName: blockchain-watcher-message-sent-events-1-pvc
        - name: jobs-volume
          configMap:
            name: {{ .NAME }}-message-sent-events-1-jobs
            items:
              - key: {{ .BLOCKCHAIN_ENV }}-jobs.json
                path: jobs.json