---          
apiVersion: v1
kind: Service
metadata:
  name: {{ .NAME }}-solana-target-events-1
  namespace: {{ .NAMESPACE }}
  labels:
    app: {{ .NAME }}-solana-target-events-1
spec:
  selector:
    app: {{ .NAME }}-solana-target-events-1
  ports:
    - port: {{ .PORT }}
      targetPort: {{ .PORT }}
      name: {{ .NAME }}-solana-target-events-1
      protocol: TCP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blockchain-watcher-solana-target-events-1-pvc
  namespace: {{ .NAMESPACE }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
  storageClassName: gp2
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .NAME }}-solana-target-events-1-jobs
  namespace: {{ .NAMESPACE }}
data:
  testnet-jobs.json: |-
    [
      {
        "id": "poll-transfer-redeemed-solana",
        "chain": "solana",
        "source": {
          "action": "PollSolanaTransactions",
          "records": "GetSolanaTransactions",
          "config": {
            "slotBatchSize": 1000,
            "commitment": "finalized",
            "interval": 1500,
            "signaturesLimit": 200,
            "programIds": [
              "DZnkkTmCiFWfYTfT41X3Rd1kDgozqzxWaHqsw6W4x2oe",
              "nTTh3bZ5Aer6xboWZe39RDEft4MeVxSQ8D1EYAVLZw9",
              "2rHhojZ7hpu1zA91nvZmT8TqWWvMcKmmNBCr2mKTtMq4"
            ],
            "chain": "solana",
            "chainId": 1
          }
        },
        "handlers": [
          {
            "action": "HandleSolanaTransactions",
            "target": "sns",
            "mapper": "solanaTransferRedeemedMapper",
            "config": {
              "programs": {
                "DZnkkTmCiFWfYTfT41X3Rd1kDgozqzxWaHqsw6W4x2oe": {
                  "instructions": ["02", "03", "09", "0a"],
                  "vaaAccountIndex": 2
                },
                "nTTh3bZ5Aer6xboWZe39RDEft4MeVxSQ8D1EYAVLZw9": {
                  "instructions": ["86d58f44eb66e860"],
                  "vaaAccountIndex": 3
                },
                "2rHhojZ7hpu1zA91nvZmT8TqWWvMcKmmNBCr2mKTtMq4": {
                    "instructions": ["02", "03"],
                    "vaaAccountIndex": 2
                }
              },
              "metricName": "process_vaa_event"
            }
          }
        ]
      }
    ]
  mainnet-jobs.json: |-
    [
      {
        "id": "poll-transfer-redeemed-solana",
        "chain": "solana",
        "source": {
          "action": "PollSolanaTransactions",
          "records": "GetSolanaTransactions",
          "config": {
            "slotBatchSize": 1000,
            "commitment": "finalized",
            "interval": 1500,
            "signaturesLimit": 200,
            "programIds": [
              "wormDTUJ6AWPNvk59vGQbDvGJmqbDTdgWgAqcLBCgUb",
              "WnFt12ZrnzZrFZkt2xsNsaNWoQribnuQ5B5FrDbwDhD",
              "NTtAaoDJhkeHeaVUHnyhwbPNAN6WgBpHkHBTc6d7vLK"
             ],
            "chain": "solana",
            "chainId": 1
          }
        },
        "handlers": [
          {
            "action": "HandleSolanaTransactions",
            "target": "sns",
            "mapper": "solanaTransferRedeemedMapper",
            "config": {
              "programs": {
                "wormDTUJ6AWPNvk59vGQbDvGJmqbDTdgWgAqcLBCgUb": {
                  "instructions": ["02", "03", "09", "0a"],
                  "vaaAccountIndex": 2
                },
                "WnFt12ZrnzZrFZkt2xsNsaNWoQribnuQ5B5FrDbwDhD": {
                    "instructions": ["02", "03"],
                    "vaaAccountIndex": 2
                },
                "NTtAaoDJhkeHeaVUHnyhwbPNAN6WgBpHkHBTc6d7vLK": {
                  "instructions": ["86d58f44eb66e860"],
                  "vaaAccountIndex": 3
                }
              },
              "metricName": "process_vaa_event"
            }
          }
        ]
      }
    ]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .NAME }}-solana-target-events-1
  namespace: {{ .NAMESPACE }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .NAME }}-solana-target-events-1
  template:
    metadata:
      labels:
        app: {{ .NAME }}-solana-target-events-1
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{ .PORT }}"
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      serviceAccountName: event-watcher
      containers:
        - name: {{ .NAME }}
          image: {{ .IMAGE_NAME }}
          env:
            - name: NODE_ENV
              value: {{ .NODE_ENV }}
            - name: PORT
              value: "{{ .PORT }}"
            - name: LOG_LEVEL
              value: {{ .LOG_LEVEL }}
            - name: BLOCKCHAIN_ENV
              value: {{ .BLOCKCHAIN_ENV }}
            - name: DRY_RUN_ENABLED
              value: "{{ .DRY_RUN_ENABLED }}"
            - name: SNS_TOPIC_ARN
              value: {{ .SNS_TOPIC_ARN }}
            - name: SNS_REGION
              value: {{ .SNS_REGION }}
            - name: NODE_OPTIONS
              value: {{ .NODE_OPTIONS }}
            - name: SOLANA_RPCS
              valueFrom:
                secretKeyRef:
                  name: blockchain-watcher
                  key: solana-urls
            - name: JOBS_DIR
              value: /home/node/app/jobs
          resources:
            limits:
              memory: {{ .RESOURCES_LIMITS_MEMORY }}
              cpu: {{ .RESOURCES_LIMITS_CPU }}
            requests:
              memory: {{ .RESOURCES_REQUESTS_MEMORY }}
              cpu: {{ .RESOURCES_REQUESTS_CPU }}
          volumeMounts:
            - name: metadata-volume
              mountPath: /home/node/app/metadata-repo 
            - name: jobs-volume
              mountPath: /home/node/app/jobs
      volumes:
        - name: metadata-volume
          persistentVolumeClaim:
            claimName: blockchain-watcher-solana-target-events-1-pvc
        - name: jobs-volume
          configMap:
            name: {{ .NAME }}-solana-target-events-1-jobs
            items:
              - key: {{ .BLOCKCHAIN_ENV }}-jobs.json
                path: jobs.json
