---     
apiVersion: v1
kind: Service
metadata:
  name: {{ .NAME }}-solana-target-events-1
  namespace: {{ .NAMESPACE }}
  labels:
    app: {{ .NAME }}-solana-target-events-1
spec:
  selector:
    app: {{ .NAME }}-solana-target-events-1
  ports:
    - port: {{ .PORT }}
      targetPort: {{ .PORT }}
      name: {{ .NAME }}-solana-target-events-1
      protocol: TCP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blockchain-watcher-solana-target-events-1-pvc
  namespace: {{ .NAMESPACE }}
  labels:
    app: {{ .NAME }}-solana-target-events-1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
  storageClassName: gp2
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .NAME }}-solana-target-events-1-jobs
  namespace: {{ .NAMESPACE }}
  labels:
    app: {{ .NAME }}-solana-target-events-1
data:
  testnet-jobs.json: |-
    [
      {
        "id": "poll-transfer-redeemed-solana",
        "chain": "solana",
        "source": {
          "action": "PollSolanaTransactions",
          "records": "GetSolanaTransactions",
          "config": {
            "slotBatchSize": 1000,
            "commitment": "finalized",
            "interval": 15000,
            "signaturesLimit": 200,
            "programIds": [
              "DZnkkTmCiFWfYTfT41X3Rd1kDgozqzxWaHqsw6W4x2oe",
              "nTTh3bZ5Aer6xboWZe39RDEft4MeVxSQ8D1EYAVLZw9",
              "2rHhojZ7hpu1zA91nvZmT8TqWWvMcKmmNBCr2mKTtMq4",
              "6afkDMjQCod662yV22tBQGArRnwhCCWHKXTpnZPqxd8",
              "mPydpGUWxzERTNpyvTKdvS7v8kvw5sgwfiP8WQFrXVS"
            ],
            "chain": "solana",
            "chainId": 1
          }
        },
        "handlers": [
          {
            "action": "HandleSolanaTransactions",
            "target": "sns",
            "mapper": "solanaTransferRedeemedMapper",
            "config": {
              "programs": {
                "DZnkkTmCiFWfYTfT41X3Rd1kDgozqzxWaHqsw6W4x2oe": [
                  {
                    "instructions": ["02", "03", "09", "0a"],
                    "vaaAccountIndex": 2
                  }
                ],
                "nTTh3bZ5Aer6xboWZe39RDEft4MeVxSQ8D1EYAVLZw9": [
                  {
                    "instructions": ["86d58f44eb66e860"],
                    "vaaAccountIndex": 3
                  }
                ],
                "2rHhojZ7hpu1zA91nvZmT8TqWWvMcKmmNBCr2mKTtMq4": [
                  {
                    "instructions": ["02", "03"],
                    "vaaAccountIndex": 2
                  }
                ],
                "6afkDMjQCod662yV22tBQGArRnwhCCWHKXTpnZPqxd8": [
                  {
                    "instructions": ["86d58f44eb66e860"],
                    "vaaAccountIndex": 3
                  }
                ],
                "mPydpGUWxzERTNpyvTKdvS7v8kvw5sgwfiP8WQFrXVS": [
                  {  
                    "instructions": ["b0261e11e64ece9d"],
                    "vaaAccountIndex": 2
                  }
                ]
              },
              "metricName": "process_vaa_event"
            }
          }
        ]
      }
    ]
  mainnet-jobs.json: |-
    [
      {
        "id": "poll-transfer-redeemed-solana",
        "chain": "solana",
        "source": {
          "action": "PollSolanaTransactions",
          "records": "GetSolanaTransactions",
          "config": {
            "slotBatchSize": 1000,
            "commitment": "finalized",
            "interval": 15000,
            "signaturesLimit": 200,
            "programIds": [
              "wormDTUJ6AWPNvk59vGQbDvGJmqbDTdgWgAqcLBCgUb",
              "WnFt12ZrnzZrFZkt2xsNsaNWoQribnuQ5B5FrDbwDhD",
              "NTtAaoDJhkeHeaVUHnyhwbPNAN6WgBpHkHBTc6d7vLK",
              "NttWixqwUHAnpXym3UYUySQZtb4C57EZxpH721JfLyF",
              "nTtPcmsVY4f86cSREmnio5tUyiK58HBqBeDwaUYQt6t",
              "NttBm3HouTCFnUBz32fEs5joQFRjFoJPA8AyhtgjFrw",
              "NTtxeqz2XjMnpcEoWMqb6pz84zHweJRYWyzmsmmW49E",
              "NttADdCvGLUhukNyePei9CkmHoe6S9xjqgqfQv51PQg",
              "NttXP2tPLxGkNA3yrSfFZbtDbfKPKBrJUR6Jcqh6sRi",
              "NTt198zrFsZkvfFH5juBK98frhDNooPtd5PGefd7vNb",
              "NtTtwqVX4SCNECrZ8ZmEaxAPFcm5r7Szx4tBmYLU17p",
              "HtkeCDdYY4i9ncAxXKjYTx8Uu3WM8JbtiLRYjtHwaVXb",
              "FC4eXxkyrMPTjiYUpp4EAnkmwMbQyZ6NDCh1kfLn6vsf",
              "A7VwadM5nSiCtmEe5XZ3AjyXBKfePF2EPnY5wZbaWJjq",
              "BopVWeP7ctdHU4x2GrbZX7XM13RPrfC45hUmcQz621Y8",
              "nTTVLsyTqRZFSyphRjkgi1Bxp5aR7nXDmMGerNWm2a6"
            ],
            "chain": "solana",
            "chainId": 1
          }
        },
        "handlers": [
          {
            "action": "HandleSolanaTransactions",
            "target": "sns",
            "mapper": "solanaTransferRedeemedMapper",
            "config": {
              "programs": {
                "wormDTUJ6AWPNvk59vGQbDvGJmqbDTdgWgAqcLBCgUb": [
                  {
                    "instructions": ["02", "03", "09", "0a"],
                    "vaaAccountIndex": 2
                  }
                ],
                "WnFt12ZrnzZrFZkt2xsNsaNWoQribnuQ5B5FrDbwDhD": [
                  {
                    "instructions": ["02", "03"],
                    "vaaAccountIndex": 2
                  }
                ],
                "NTtAaoDJhkeHeaVUHnyhwbPNAN6WgBpHkHBTc6d7vLK": [
                  {
                    "instructions": ["86d58f44eb66e860"],
                    "vaaAccountIndex": 3
                  }
                ],
                "NttWixqwUHAnpXym3UYUySQZtb4C57EZxpH721JfLyF": [
                  {
                    "instructions": ["86d58f44eb66e860"],
                    "vaaAccountIndex": 3
                  }
                ],
                "nTtPcmsVY4f86cSREmnio5tUyiK58HBqBeDwaUYQt6t": [
                  {
                    "instructions": ["86d58f44eb66e860"],
                    "vaaAccountIndex": 3
                  }
                ],
                "NttBm3HouTCFnUBz32fEs5joQFRjFoJPA8AyhtgjFrw": [
                  {
                    "instructions": ["86d58f44eb66e860"],
                    "vaaAccountIndex": 3
                  }
                ],
                "NTtxeqz2XjMnpcEoWMqb6pz84zHweJRYWyzmsmmW49E": [
                  {
                    "instructions": ["86d58f44eb66e860"],
                    "vaaAccountIndex": 3
                  }
                ],
                "NttADdCvGLUhukNyePei9CkmHoe6S9xjqgqfQv51PQg": [
                  {
                    "instructions": ["86d58f44eb66e860"],
                    "vaaAccountIndex": 3
                  }
                ],
                "NttXP2tPLxGkNA3yrSfFZbtDbfKPKBrJUR6Jcqh6sRi": [
                  {
                    "instructions": ["86d58f44eb66e860"],
                    "vaaAccountIndex": 3
                  }
                ],
                "NTt198zrFsZkvfFH5juBK98frhDNooPtd5PGefd7vNb": [
                  {
                    "instructions": ["86d58f44eb66e860"],
                    "vaaAccountIndex": 3
                  }
                ],
                "NtTtwqVX4SCNECrZ8ZmEaxAPFcm5r7Szx4tBmYLU17p": [
                  {
                    "instructions": ["86d58f44eb66e860"],
                    "vaaAccountIndex": 3
                  }
                ],
                "HtkeCDdYY4i9ncAxXKjYTx8Uu3WM8JbtiLRYjtHwaVXb": [
                  {
                    "instructions": ["ddb2b82bf7f85aa0"],
                    "vaaAccountIndex": 2
                  },
                  {
                    "instructions": ["b0261e11e64ece9d"],
                    "vaaAccountIndex": 4
                  }
                ],
                "FC4eXxkyrMPTjiYUpp4EAnkmwMbQyZ6NDCh1kfLn6vsf": [
                  {
                    "instructions": ["64"],
                    "vaaAccountIndex": 2
                  }
                ],
                "A7VwadM5nSiCtmEe5XZ3AjyXBKfePF2EPnY5wZbaWJjq": [
                  {
                    "instructions": ["86d58f44eb66e860"],
                    "vaaAccountIndex": 3
                  }
                ],
                "BopVWeP7ctdHU4x2GrbZX7XM13RPrfC45hUmcQz621Y8": [
                  {
                    "instructions": ["86d58f44eb66e860"],
                    "vaaAccountIndex": 3
                  }
                ],
                "nTTVLsyTqRZFSyphRjkgi1Bxp5aR7nXDmMGerNWm2a6": [
                  {
                    "instructions": ["86d58f44eb66e860"],
                    "vaaAccountIndex": 3
                  }
                ]
              },
              "metricName": "process_vaa_event"
            }
          }
        ]
      }
    ]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .NAME }}-solana-target-events-1
  namespace: {{ .NAMESPACE }}
  labels:
    app: {{ .NAME }}-solana-target-events-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .NAME }}-solana-target-events-1
  strategy: # Rolling update strategy for restarting the pods
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: {{ .NAME }}-solana-target-events-1
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{ .PORT }}"
    spec:
      containers:
        - name: {{ .NAME }}
          image: {{ .IMAGE_NAME }} # Docker image
          env:
            - name: NODE_ENV
              value: {{ .NODE_ENV }}
            - name: PORT
              value: "{{ .PORT }}"
            - name: LOG_LEVEL
              value: {{ .LOG_LEVEL }}
            - name: BLOCKCHAIN_ENV
              value: {{ .BLOCKCHAIN_ENV }}
            - name: DRY_RUN_ENABLED
              value: "{{ .DRY_RUN_ENABLED }}"
            - name: SNS_TOPIC_ARN
              value: {{ .SNS_TOPIC_ARN }}
            - name: SNS_REGION
              value: {{ .SNS_REGION }}
            - name: NODE_OPTIONS
              value: {{ .NODE_OPTIONS }}
            - name: JOBS_DIR
              value: /home/node/app/jobs
            {{ if .SOLANA_RPCS }}
            - name: SOLANA_RPCS
              value: '{{ .SOLANA_RPCS }}'
            {{ end }}
          resources:
            limits:
              cpu: {{ .SOLANA_RESOURCES_LIMITS_CPU }}
              memory: {{ .SOLANA_RESOURCES_LIMITS_MEMORY }}
            requests:
              cpu: {{ .SOLANA_RESOURCES_REQUESTS_CPU }}
              memory: {{ .SOLANA_RESOURCES_REQUESTS_MEMORY }}
          volumeMounts:
            - name: metadata-volume
              mountPath: /home/node/app/metadata-repo 
            - name: jobs-volume
              mountPath: /home/node/app/jobs
      restartPolicy: Always
      serviceAccountName: blockchain-watcher
      terminationGracePeriodSeconds: 30
      volumes:
        - name: metadata-volume
          persistentVolumeClaim:
            claimName: blockchain-watcher-solana-target-events-1-pvc
        - name: jobs-volume
          configMap:
            name: {{ .NAME }}-solana-target-events-1-jobs
            items:
              - key: {{ .BLOCKCHAIN_ENV }}-jobs.json
                path: jobs.json